const state = {
  articles: [],
  filtered: [],
  analysis: null,
  rawData: null,
  lang: localStorage.getItem("newsLang") || "en",
};

const i18n = {
  en: {
    eyebrow: "Semiconductor intelligence",
    title: "Industry News Watch",
    lastUpdate: "Last update",
    loading: "Loading...",
    unable: "Unable to load news",
    unavailable: "News data is not available yet. Run the update workflow to refresh it.",
    waiting: "Waiting for first update",
    search: "Search",
    searchPlaceholder: "Company, foundry, AI chip, policy...",
    category: "Category",
    source: "Source",
    sort: "Sort",
    allCategories: "All categories",
    allSources: "All sources",
    importanceFirst: "Importance first",
    newestFirst: "Newest first",
    sourceSort: "Source",
    categorySort: "Category",
    totalStories: "Total stories",
    sources: "Sources",
    important: "Important",
    refreshCadence: "Refresh cadence",
    hourly: "Hourly",
    importantFilter: "Important News Filter",
    newsSummary: "News Summary",
    autoGenerated: "Auto generated",
    marketSignals: "News-Based Market Signals",
    watchlistNote: "Watchlist, not financial advice",
    usMarket: "US Market",
    chinaMarket: "China Market",
    savedFeed: "Saved News Feed",
    highlighted: "highlighted",
    results: "results",
    result: "result",
    noMatch: "No matching stories found.",
    noStrongSignals: "No strong news-linked stock signals in the current filter.",
    noSummary: "No summary provided.",
    undated: "Undated",
    unknown: "Unknown source",
    industry: "Industry",
    risk: "News signal only. Validate valuation, liquidity, earnings dates, and regulatory risk before acting.",
  },
  zh: {
    eyebrow: "半导体情报",
    title: "行业新闻观察站",
    lastUpdate: "最近更新",
    loading: "加载中...",
    unable: "无法加载新闻",
    unavailable: "新闻数据暂时不可用。请运行更新工作流刷新数据。",
    waiting: "等待首次更新",
    search: "搜索",
    searchPlaceholder: "公司、晶圆代工、AI 芯片、政策...",
    category: "类别",
    source: "来源",
    sort: "排序",
    allCategories: "全部类别",
    allSources: "全部来源",
    importanceFirst: "重要性优先",
    newestFirst: "最新优先",
    sourceSort: "来源",
    categorySort: "类别",
    totalStories: "新闻总数",
    sources: "来源数量",
    important: "重点新闻",
    refreshCadence: "更新频率",
    hourly: "每小时",
    importantFilter: "重点新闻筛选",
    newsSummary: "新闻摘要",
    autoGenerated: "自动生成",
    marketSignals: "基于新闻的市场信号",
    watchlistNote: "观察清单，不构成投资建议",
    usMarket: "美国市场",
    chinaMarket: "中国市场",
    savedFeed: "已保存新闻流",
    highlighted: "条重点",
    results: "条结果",
    result: "条结果",
    noMatch: "没有找到匹配的新闻。",
    noStrongSignals: "当前筛选条件下没有明显的新闻关联股票信号。",
    noSummary: "暂无摘要。",
    undated: "无日期",
    unknown: "未知来源",
    industry: "行业",
    risk: "仅为新闻信号观察，不是个性化投资建议。操作前请自行核查估值、流动性、财报日期和监管风险。",
  },
};

const categoryZh = {
  "AI Hardware": "AI 硬件",
  "Foundry": "晶圆代工",
  "Equipment": "半导体设备",
  "Memory": "存储芯片",
  "EDA and IP": "EDA 与 IP",
  "Policy and Supply Chain": "政策与供应链",
  "Automotive": "汽车芯片",
  "Manufacturing": "制造",
  "Semiconductors": "半导体",
  "Hardware": "硬件",
  "Compute": "计算",
  "Datacenter": "数据中心",
  "Research": "研究",
  "Asia Supply Chain": "亚洲供应链",
};

const keywordZh = {
  semiconductor: "半导体", semiconductors: "半导体", chip: "芯片", chips: "芯片", chipmaker: "芯片厂商",
  silicon: "硅", foundry: "晶圆代工", fab: "晶圆厂", wafer: "晶圆", memory: "存储", dram: "DRAM", nand: "NAND",
  hbm: "HBM", gpu: "GPU", "ai chip": "AI 芯片", "ai accelerator": "AI 加速器", datacenter: "数据中心",
  "data center": "数据中心", packaging: "封装", "advanced packaging": "先进封装", lithography: "光刻",
  "export control": "出口管制", "chips act": "芯片法案", "supply chain": "供应链", sanction: "制裁", sanctions: "制裁",
  tariff: "关税", "chip design": "芯片设计", "chip equipment": "半导体设备",
};

const elements = {
  lastUpdated: document.querySelector("#lastUpdated"),
  totalStories: document.querySelector("#totalStories"),
  totalSources: document.querySelector("#totalSources"),
  importantStories: document.querySelector("#importantStories"),
  resultCount: document.querySelector("#resultCount"),
  highlightCount: document.querySelector("#highlightCount"),
  highlightList: document.querySelector("#highlightList"),
  summaryText: document.querySelector("#summaryText"),
  themeList: document.querySelector("#themeList"),
  usSignals: document.querySelector("#usSignals"),
  chinaSignals: document.querySelector("#chinaSignals"),
  newsList: document.querySelector("#newsList"),
  emptyState: document.querySelector("#emptyState"),
  searchInput: document.querySelector("#searchInput"),
  categoryFilter: document.querySelector("#categoryFilter"),
  sourceFilter: document.querySelector("#sourceFilter"),
  sortSelect: document.querySelector("#sortSelect"),
  template: document.querySelector("#articleTemplate"),
  langButtons: document.querySelectorAll(".lang-button"),
};

const t = (key) => i18n[state.lang][key] || i18n.en[key] || key;
const labelCategory = (value) => state.lang === "zh" ? (categoryZh[value] || value) : value;
const labelKeyword = (value) => state.lang === "zh" ? (keywordZh[String(value).toLowerCase()] || value) : value;

async function loadNews() {
  applyLanguage();
  try {
    const response = await fetch(`data/news.json?ts=${Date.now()}`);
    if (!response.ok) throw new Error(`News data failed with ${response.status}`);

    const data = await response.json();
    state.rawData = data;
    state.articles = Array.isArray(data.articles) ? data.articles : [];
    state.analysis = normalizeAnalysis(data);
    updateMetadata(data);
    populateFilters();
    applyFilters();
  } catch (error) {
    elements.lastUpdated.textContent = t("unable");
    elements.newsList.innerHTML = "";
    elements.emptyState.hidden = false;
    elements.emptyState.textContent = t("unavailable");
    console.error(error);
  }
}

function applyLanguage() {
  document.documentElement.lang = state.lang === "zh" ? "zh-CN" : "en";
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    node.textContent = t(node.dataset.i18n);
  });
  elements.searchInput.placeholder = t("searchPlaceholder");
  elements.langButtons.forEach((button) => button.classList.toggle("active", button.dataset.lang === state.lang));
  setSortLabels();
}

function setSortLabels() {
  const labels = {
    importance: t("importanceFirst"),
    newest: t("newestFirst"),
    source: t("sourceSort"),
    category: t("categorySort"),
  };
  [...elements.sortSelect.options].forEach((option) => {
    option.textContent = labels[option.value] || option.textContent;
  });
}

function updateMetadata(data) {
  const updatedAt = data.updatedAt ? new Date(data.updatedAt) : null;
  elements.lastUpdated.textContent = updatedAt && !Number.isNaN(updatedAt.getTime())
    ? updatedAt.toLocaleString(state.lang === "zh" ? "zh-CN" : undefined, { dateStyle: "medium", timeStyle: "short" })
    : t("waiting");

  elements.totalStories.textContent = state.articles.length.toString();
  elements.totalSources.textContent = new Set(state.articles.map((item) => item.source)).size.toString();
  elements.importantStories.textContent = state.articles.filter((item) => (item.importanceScore || 0) >= 7).length.toString();
}

function populateFilters() {
  fillSelect(elements.categoryFilter, uniqueValues("category"), t("allCategories"), labelCategory);
  fillSelect(elements.sourceFilter, uniqueValues("source"), t("allSources"));
}

function uniqueValues(key) {
  return [...new Set(state.articles.map((item) => item[key]).filter(Boolean))].sort((a, b) => a.localeCompare(b));
}

function fillSelect(select, values, defaultLabel, labeler = (value) => value) {
  const current = select.value;
  select.innerHTML = `<option value="all">${defaultLabel}</option>`;
  values.forEach((value) => {
    const option = document.createElement("option");
    option.value = value;
    option.textContent = labeler(value);
    select.append(option);
  });
  select.value = values.includes(current) ? current : "all";
}

function applyFilters() {
  const query = elements.searchInput.value.trim().toLowerCase();
  const category = elements.categoryFilter.value;
  const source = elements.sourceFilter.value;

  state.filtered = state.articles.filter((article) => {
    const haystack = [article.title, article.summary, article.source, article.category, labelCategory(article.category), ...(article.keywords || [])]
      .join(" ")
      .toLowerCase();

    return (!query || haystack.includes(query))
      && (category === "all" || article.category === category)
      && (source === "all" || article.source === source);
  });

  sortArticles();
  renderAnalysis();
  renderArticles();
}

function sortArticles() {
  const sortMode = elements.sortSelect.value;
  state.filtered.sort((a, b) => {
    if (sortMode === "source") return a.source.localeCompare(b.source) || newestFirst(a, b);
    if (sortMode === "category") return a.category.localeCompare(b.category) || newestFirst(a, b);
    if (sortMode === "newest") return newestFirst(a, b);
    return (b.importanceScore || 0) - (a.importanceScore || 0) || newestFirst(a, b);
  });
}

function newestFirst(a, b) {
  return new Date(b.publishedAt || 0) - new Date(a.publishedAt || 0);
}

function renderAnalysis() {
  const analysis = buildVisibleAnalysis();
  renderHighlights(analysis.highlights || []);
  renderSummary(analysis.summary, analysis.themes || []);
  renderSignals(elements.usSignals, analysis.marketSignals?.us || []);
  renderSignals(elements.chinaSignals, analysis.marketSignals?.china || []);
}

function normalizeAnalysis(data) {
  const fallback = buildAnalysisFromArticles(state.articles);
  return {
    summary: data.summary || fallback.summary,
    themes: Array.isArray(data.themes) && data.themes.length ? data.themes : fallback.themes,
    highlights: Array.isArray(data.highlights) && data.highlights.length ? data.highlights : fallback.highlights,
    marketSignals: {
      us: data.marketSignals?.us?.length ? data.marketSignals.us : fallback.marketSignals.us,
      china: data.marketSignals?.china?.length ? data.marketSignals.china : fallback.marketSignals.china,
    },
  };
}

function buildVisibleAnalysis() {
  if (state.lang === "zh" || state.filtered.length !== state.articles.length) return buildAnalysisFromArticles(state.filtered);
  return state.analysis;
}

function buildAnalysisFromArticles(articles) {
  const scored = articles.map((article) => ({ ...article, importanceScore: article.importanceScore || scoreArticle(article) }))
    .sort((a, b) => (b.importanceScore || 0) - (a.importanceScore || 0) || newestFirst(a, b));
  const themes = topThemes(scored);
  return {
    highlights: scored.slice(0, 5).map((article) => ({
      title: article.title,
      url: article.url,
      source: article.source,
      category: article.category,
      importanceScore: article.importanceScore,
      reason: reasonForArticle(article),
    })),
    summary: summarizeThemes(scored, themes),
    themes,
    marketSignals: buildMarketSignals(scored),
  };
}

function scoreArticle(article) {
  const text = `${article.title} ${article.summary} ${(article.keywords || []).join(" ")}`.toLowerCase();
  const weights = [
    ["nvidia", 3], ["tsmc", 3], ["asml", 3], ["hbm", 3], ["export control", 3], ["chips act", 3],
    ["ai chip", 2], ["gpu", 2], ["foundry", 2], ["fab", 2], ["memory", 2], ["earnings", 2],
    ["guidance", 2], ["sanction", 2], ["supply chain", 2], ["advanced packaging", 2],
  ];
  return Math.min(10, 2 + weights.reduce((sum, [term, weight]) => sum + (text.includes(term) ? weight : 0), 0));
}

function reasonForArticle(article) {
  const terms = (article.keywords || []).slice(0, 3).map(labelKeyword).join(state.lang === "zh" ? "、" : ", ") || labelCategory(article.category) || t("industry");
  if (state.lang === "zh") return `被标记为重点，因为它涉及 ${terms}，可能影响芯片需求、产能、价格或供应链。`;
  return `Flagged because it touches ${terms}, which can affect chip demand, capacity, pricing, or supply chains.`;
}

function topThemes(articles) {
  const counts = new Map();
  articles.forEach((article) => {
    if (!article.category) return;
    counts.set(article.category, (counts.get(article.category) || 0) + 1);
  });
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([name, count]) => ({ name, count }));
}

function summarizeThemes(articles, themes) {
  if (!articles.length) return state.lang === "zh" ? "当前筛选条件下还没有匹配的半导体新闻。" : "No matching semiconductor news is available for this filter yet.";
  const themeText = themes.map((theme) => labelCategory(theme.name)).join(state.lang === "zh" ? "、" : ", ") || (state.lang === "zh" ? "半导体行业动态" : "semiconductor activity");
  const important = articles.filter((article) => (article.importanceScore || 0) >= 7).length;
  if (state.lang === "zh") {
    return `当前追踪 ${articles.length} 条相关半导体新闻。主要主题集中在 ${themeText}。其中 ${important} 条被标记为重点，依据包括公司提及度、供应链影响、政策风险、产能变化、AI 硬件需求，以及存储或设备信号。`;
  }
  return `${articles.length} relevant stories are being tracked. The strongest themes are ${themeText}. ${important} stories are currently flagged as high importance based on company mentions, supply-chain impact, policy risk, capacity changes, AI hardware demand, or memory/equipment signals.`;
}

const MARKET_MAP = {
  us: [
    { ticker: "NVDA", name: "NVIDIA", terms: ["nvidia", "gpu", "ai chip", "accelerator", "hbm", "blackwell", "rubin"] },
    { ticker: "AMD", name: "Advanced Micro Devices", terms: ["amd", "gpu", "ai chip", "accelerator", "server cpu"] },
    { ticker: "INTC", name: "Intel", terms: ["intel", "intel foundry", "fab", "process node", "pc chip"] },
    { ticker: "TSM", name: "TSMC ADR", terms: ["tsmc", "foundry", "wafer", "advanced packaging"] },
    { ticker: "ASML", name: "ASML ADR", terms: ["asml", "lithography", "euv", "duv"] },
    { ticker: "MU", name: "Micron", terms: ["micron", "memory", "dram", "nand", "hbm"] },
    { ticker: "AVGO", name: "Broadcom", terms: ["broadcom", "asic", "networking chip", "ai infrastructure"] },
    { ticker: "AMAT", name: "Applied Materials", terms: ["applied materials", "chip equipment", "semiconductor tools"] },
    { ticker: "LRCX", name: "Lam Research", terms: ["lam research", "etch", "deposition", "chip equipment"] },
    { ticker: "CDNS", name: "Cadence", terms: ["cadence", "eda", "chip design"] },
    { ticker: "SNPS", name: "Synopsys", terms: ["synopsys", "eda", "chip design"] },
  ],
  china: [
    { ticker: "0981.HK / 688981.SS", name: "SMIC", terms: ["smic", "china foundry", "foundry", "fab"] },
    { ticker: "1347.HK / 688347.SS", name: "Hua Hong Semiconductor", terms: ["hua hong", "foundry", "china chip"] },
    { ticker: "002371.SZ", name: "NAURA", terms: ["naura", "chip equipment", "semiconductor tools"] },
    { ticker: "688012.SS", name: "AMEC", terms: ["amec", "etch", "chip equipment"] },
    { ticker: "600584.SS", name: "JCET", terms: ["jcet", "advanced packaging", "packaging"] },
    { ticker: "603501.SS", name: "Will Semiconductor", terms: ["will semiconductor", "image sensor", "automotive chip"] },
    { ticker: "688008.SS", name: "Montage Technology", terms: ["montage", "memory interface", "dram", "server memory"] },
    { ticker: "688256.SS", name: "Cambricon", terms: ["cambricon", "ai chip", "accelerator"] },
    { ticker: "688041.SS", name: "Hygon", terms: ["hygon", "server cpu", "cpu"] },
    { ticker: "Huawei supply chain", name: "Huawei-related chip supply chain", terms: ["huawei", "sanctions", "china", "chip design"] },
  ],
};

function buildMarketSignals(articles) {
  return {
    us: scoreMarket(MARKET_MAP.us, articles),
    china: scoreMarket(MARKET_MAP.china, articles),
  };
}

function scoreMarket(stocks, articles) {
  return stocks.map((stock) => {
    const matching = articles.filter((article) => {
      const text = `${article.title} ${article.summary} ${(article.keywords || []).join(" ")}`.toLowerCase();
      return stock.terms.some((term) => text.includes(term));
    });
    const score = Math.min(10, matching.reduce((sum, article) => sum + Math.max(1, Math.round((article.importanceScore || 4) / 3)), 0));
    return {
      ...stock,
      score,
      rationale: matching.length
        ? (state.lang === "zh"
          ? `检测到 ${matching.length} 条相关新闻；请继续观察订单、利润率、产能或政策敞口是否有后续变化。`
          : `${matching.length} related story${matching.length === 1 ? "" : "ies"} detected; watch for follow-through in orders, margins, capacity, or policy exposure.`)
        : (state.lang === "zh" ? "当前筛选条件下没有直接的高信号新闻匹配。" : "No direct high-signal article match in the current filter."),
      risk: t("risk"),
    };
  }).filter((stock) => stock.score > 0).sort((a, b) => b.score - a.score).slice(0, 6);
}

function renderHighlights(highlights) {
  elements.highlightList.innerHTML = "";
  elements.highlightCount.textContent = `${highlights.length} ${t("highlighted")}`;
  highlights.forEach((item) => {
    const row = document.createElement("article");
    row.className = "highlight-item";
    const score = item.importanceScore || scoreArticle(item);
    const reason = state.lang === "zh" ? reasonForArticle(item) : (item.reason || item.whyImportant || reasonForArticle(item));
    row.innerHTML = `
      <div class="card-meta">
        <span class="importance">${score}/10</span>
        <span class="category">${labelCategory(item.category || t("industry"))}</span>
        <span class="source">${item.source || t("unknown")}</span>
      </div>
      <strong><a href="${item.url}" target="_blank" rel="noopener noreferrer">${item.title}</a></strong>
      <p class="highlight-reason">${reason}</p>
    `;
    elements.highlightList.append(row);
  });
}

function renderSummary(summary, themes) {
  elements.summaryText.textContent = state.lang === "zh" ? summarizeThemes(state.filtered, topThemes(state.filtered)) : summary;
  elements.themeList.innerHTML = "";
  themes.forEach((theme) => {
    const chip = document.createElement("div");
    chip.className = "theme-chip";
    chip.innerHTML = `<span>${labelCategory(theme.name)}</span><span>${theme.count}</span>`;
    elements.themeList.append(chip);
  });
}

function renderSignals(container, signals) {
  container.innerHTML = "";
  if (!signals.length) {
    container.innerHTML = `<p class="briefing-text">${t("noStrongSignals")}</p>`;
    return;
  }
  signals.forEach((signal) => {
    const card = document.createElement("article");
    card.className = "signal-card";
    card.innerHTML = `
      <header>
        <div><strong>${signal.ticker}</strong><small> ${signal.name}</small></div>
        <span class="signal-score">${signal.score}/10</span>
      </header>
      <p class="signal-rationale">${signal.rationale}</p>
      <p class="signal-risk">${signal.risk || t("risk")}</p>
    `;
    container.append(card);
  });
}

function renderArticles() {
  elements.newsList.innerHTML = "";
  elements.resultCount.textContent = `${state.filtered.length} ${state.filtered.length === 1 ? t("result") : t("results")}`;
  elements.emptyState.hidden = state.filtered.length > 0;
  elements.emptyState.textContent = t("noMatch");

  state.filtered.forEach((article) => {
    const card = elements.template.content.cloneNode(true);
    const link = card.querySelector("a");
    const time = card.querySelector("time");
    const keywordRow = card.querySelector(".keyword-row");
    const score = article.importanceScore || scoreArticle(article);
    const importance = card.querySelector(".importance");

    importance.textContent = `${score}/10`;
    importance.classList.toggle("medium", score < 7 && score >= 4);
    importance.classList.toggle("low", score < 4);
    card.querySelector(".category").textContent = labelCategory(article.category || t("industry"));
    card.querySelector(".source").textContent = article.source || t("unknown");
    link.href = article.url;
    link.textContent = article.title;
    card.querySelector(".summary").textContent = state.lang === "zh" ? chineseArticleSummary(article) : (article.summary || t("noSummary"));

    const publishedAt = article.publishedAt ? new Date(article.publishedAt) : null;
    time.dateTime = publishedAt ? publishedAt.toISOString() : "";
    time.textContent = publishedAt && !Number.isNaN(publishedAt.getTime())
      ? publishedAt.toLocaleDateString(state.lang === "zh" ? "zh-CN" : undefined, { month: "short", day: "numeric" })
      : t("undated");

    (article.keywords || []).slice(0, 5).forEach((keyword) => {
      const chip = document.createElement("span");
      chip.textContent = labelKeyword(keyword);
      keywordRow.append(chip);
    });

    elements.newsList.append(card);
  });
}

function chineseArticleSummary(article) {
  const category = labelCategory(article.category || t("industry"));
  const source = article.source || t("unknown");
  const terms = (article.keywords || []).slice(0, 4).map(labelKeyword).join("、") || category;
  return `这条来自 ${source} 的新闻聚焦 ${category}，关键词包括 ${terms}。请点击标题查看原文细节；该站点会优先标记可能影响需求、产能、价格、政策或供应链的内容。`;
}

[elements.searchInput, elements.categoryFilter, elements.sourceFilter, elements.sortSelect].forEach((control) => {
  control.addEventListener("input", applyFilters);
  control.addEventListener("change", applyFilters);
});

elements.langButtons.forEach((button) => {
  button.addEventListener("click", () => {
    state.lang = button.dataset.lang;
    localStorage.setItem("newsLang", state.lang);
    applyLanguage();
    updateMetadata(state.rawData || {});
    populateFilters();
    applyFilters();
  });
});

loadNews();
